
function CDialogo(sesionActual){this.SesionActual=sesionActual;this.dialogoActual=new Dialogo();this.tipodeMovidasActuales;this.categoriasActuales;this.categoriaSeleccionada;this.reglasActuales=new Array();this.usuarioFacilitadorActual;this.usuariosPermitidosActuales;this.balanceActual;this.reglasDisponibles;{this.getIntervencionesActuales=function(){try{return this.dialogoActual.intervenciones;}
catch(ex){var arr=new Array();return arr;}}}}
CDialogo.prototype.actualizarCategoriasPosibles=function(){this.cateogriasActuales=new Array();try{var _cl=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));this.categoriasActuales=_cl.conexion("listarCategoriasMovida",parametros);this.categoriasActuales.pop();for(var i=0;i<this.categoriasActuales.length;i++){this.categoriasActuales[i].movidas.pop();}}catch(ex){}}
CDialogo.prototype.obtenerMovidaPredeterminada=function(idPerfil){var _ret=0;try{var _servicio=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("iddialogo",idPerfil);_ret=_servicio.conexion("obtenerMovidaCrearDialogo",parametros);}catch(ex){return 0;}
return _ret;}
CDialogo.prototype.determinarCategoriaSeleccionada=function(){try{if((this.dialogoActual.balanceDialogo!=null&&this.dialogoActual.balanceDialogo.length>0)&&this.categoriaSeleccionada==null){var pivote=this.balanceActual[0].movida;for(var i=0;i<this.dialogoActual.categoria.movidas.length;i++){if(this.dialogoActual.categoria.movidas[i].IdMovida==pivote.IdMovida){pivote=this.dialogoActual.categoria.movidas[i];break;}}
for(var i=0;i<this.categoriasActuales.length;i++){if(this.categoriasActuales[i].movidas.length==this.balanceActual.length){for(var j=0;j<this.categoriasActuales[i].movidas.length;j++){if(this.categoriasActuales[i].movidas[j].Nombre==pivote.Nombre){this.categoriaSeleccionada=this.categoriasActuales[i];this.categoriasActuales[i].movidas=this.dialogoActual.categoria.movidas;return;}}}}}}catch(ex){}}
CDialogo.prototype.listarDialogos=function(sesionActual,pagina,_msgError){var _retorno=new Array();try{var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(sesionActual));parametros.add("pagina",JSON.stringify(pagina));_retorno=_cm.conexion("listarEncabezadosDialogo",parametros);}catch(ex){notificar("No se pudo conectar con el servicio.");}
return _retorno;}
CDialogo.prototype.actualizarDialogoActual=function(idDialogo){_int=new Intervencion();try{var _conexion=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("iddialogo",JSON.stringify(idDialogo));this.dialogoActual=_conexion.conexion("obtenerDialogoDetallado",parametros);this.dialogoActual.categoria.movidas.pop();this.dialogoActual.intervenciones.pop();this.dialogoActual.Reglas.pop();this.dialogoActual.balanceDialogo.pop();_conexion=new ConexionManager();parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("iddialogo",JSON.stringify(idDialogo));this.tipodeMovidasActuales=_conexion.conexion("obtenerMovidasDialogo",parametros);this.reglasActuales=this.dialogoActual.Reglas;this.usuariosPermitidosActuales=this.dialogoActual.usuariosPermitidos;if(this.dialogoActual.balanceDialogo!=null){this.balanceActual=this.dialogoActual.balanceDialogo;}
return true;}catch(ex){alert("Error al obtener las intervenciones desde el servicio web.\nNO se mostrará la página.\n\n"+ex);window.close();}
return false;}
CDialogo.prototype.obtenerTodasLasActas=function(){var _retorno=new Array();var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("dialogo",JSON.stringify(this.dialogoActual))
_retorno=_cm.conexion("listarTodasLasActas",parametros);_retorno.pop();return _retorno;}
CDialogo.prototype.hayDialogosDesbalanceados=function(){try{var lista=this.obtenerDialogosDesbalanceados();if(lista.length>0)
return true;else
return false;}catch(ex){return false;}}
CDialogo.prototype.obtenerDialogosDesbalanceados=function(){var _retorno=new Array();try{var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));_retorno=_cm.conexion("listarAlertas",parametros);}catch(ex){}
return _retorno;}
CDialogo.prototype.obtenerEstadisticas=function(dialog){var _ret=new Object();try{var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("dialogo",JSON.stringify(dialog));_ret=_cm.conexion("obtenerEstadisticas",parametros);}catch(ex){}
return _ret;}
CDialogo.prototype.guardarConfiguracionDialogo=function(){var _retorno=false;try{this.dialogoActual.balanceDialogo=this.balanceActual;this.dialogoActual.usuarioFacilitador=this.usuarioFacilitadorActual;this.dialogoActual.Reglas=this.reglasActuales;this.dialogoActual.usuariosPermitidos=this.usuariosPermitidosActuales;var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));var dialogo=this.dialogoActual;dialogo.intervenciones=null;dialogo.ActaUsuario=null;parametros.add("dialogo",JSON.stringify(this.dialogoActual));_retorno=_cm.conexion("guardarConfiguracionDialogo",parametros);}catch(ex){}
return _retorno;}
CDialogo.prototype.crearDialogoVacio=function(){try{var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));this.dialogoActual=_cm.conexion("crearDialogo",parametros);this.dialogoActual=JSON.parse(this.dialogoActual);this.dialogoActual.usuarioCreador=this.SesionActual.usuario;if(this.categoriasActuales==null||this.categoriaSeleccionada==null){this.actualizarCategoriasPosibles();if(this.categoriasActuales.length>0){this.categoriaSeleccionada=this.categoriasActuales[0];}}
this.balanceActual=this.dialogoActual.balanceDialogo;return true;}catch(ex){return false;}}
CDialogo.prototype.publicarIntervencion=function(intervencionOrigen,texto,codigoMovida){var _retorno=false;try{var _nueva=new Intervencion();_nueva.intervencionRespuesta=intervencionOrigen;_nueva.TextoRespuesta=intervencionOrigen.TextoRespuesta;_nueva.tipoMovida=codigoMovida;_nueva.usuarioCreador=this.SesionActual.usuario;_nueva.Texto=texto;var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("dialogo",JSON.stringify(this.dialogoActual));parametros.add("intervencion",JSON.stringify(_nueva));_retorno=_cm.conexion("publicarIntervencion",parametros);}catch(ex){}
return _retorno;}
CDialogo.prototype.publicarDialogo=function(dialogo,mensajeError){var _ret=false;try{var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("dialogo",JSON.stringify(dialogo));_ret=_cm.conexion("publicarDialogo",parametros);if(!_ret){}
return _ret;}catch(ex){mensajeError="No se pudo conectar con el servicio."}
return _ret;}
CDialogo.prototype.guardarSugerencia=function(intervencion,movida,mensajeError){var _ret=false;try{var _cm=new ConexionManager();var _mov=new MovidaCorregida();_mov.IdMovida=movida.IdMovida;_mov.Nombre=movida.Nombre;intervencion.correccionMovida[0]=_mov;var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));parametros.add("intervencion",JSON.stringify(intervencion));_ret=_cm.conexion("guardarCorreccion",parametros);if(!_ret){}}catch(ex){}
return _ret;}
CDialogo.prototype.ReglasDisponibles=function(){if(this.reglasDisponibles==null||this.reglasDisponibles.length==0){var _cm=new ConexionManager();var parametros=new SOAPClientParameters();parametros.add("sesion",JSON.stringify(this.SesionActual));this.reglasDisponibles=_cm.conexion("listarReglasDisponibles",parametros);this.reglasDisponibles.pop();}
return this.reglasDisponibles;}
CDialogo.prototype.buscarHijos=function(intervencionSeleccionada){var _listaHijos=new Array();_listaHijos.push(intervencionSeleccionada);var intervencionesActuales=this.getIntervencionesActuales();for(var i=0;i<intervencionesActuales.length;i++){if(intervencionesActuales[i]!=null&&intervencionesActuales[i].intervencionRespuesta!=null){if(this.ListaContiene(_listaHijos,intervencionesActuales[i].intervencionRespuesta)&&!this.estaEn(_listaHijos,intervencionesActuales[i])){_listaHijos.push(intervencionesActuales[i]);}}}
return _listaHijos;}
CDialogo.prototype.estaEn=function(_arreglo,objeto){for(var i=0;i<_arreglo.length;i++){if(_arreglo[i]==objeto){return true;}}
return false;}
CDialogo.prototype.ListaContiene=function(lista,elemento){for(var i=0;i<lista.length;i++){if(lista[i].idIntervencion==elemento.idIntervencion){return true;}}
return false;}