
function hola(event){var p=event;p=0;}
$(function(){});function DialogBrowser(){this.coleccionNodos=new Array();this.intervenciones=new Array();this.posx=1;this.ultimoUsuario="";this.Padre;}
DialogBrowser.prototype.refrescar=function(){this.coleccionNodos=new Array();try{$("div#dialogBrowser div, div#dialogBrowser hr").remove();$("div#dialogBrowser div, div#dialogBrowser hr").unbind();this.posx=1;}catch(ex){}
var _intervenciones=this.intervenciones;for(var i=0;i<_intervenciones.length;i=i+1){var _nuevo=new NodoBrowser(_intervenciones[i]);if(_intervenciones[i].intervencionRespuesta==null){_nuevo.setCoordenadaX(1);_nuevo.setCoordenadaY(1);this.ultimoUsuario=_intervenciones[i].usuarioCreador.nombreUsuario;this.agregarNodoSolitario(_nuevo);this.coleccionNodos.push(_nuevo);}else{this.agregarNodoVecino(_nuevo,_intervenciones[i].intervencionRespuesta);this.coleccionNodos.push(_nuevo);}}}
function buscarIntervencionPorId(id,_intervenciones){for(var i=0;i<_intervenciones.length;i++){if(_intervenciones[i].id.toString()==id.toString()){return _intervenciones[i];}}
return null;}
function btnSeleccionarNodo_Click(event,_navegadorHilo){$("body").css("cursor","wait");var _botonPresionado;var _copiaPadre=event.target.id.lastIndexOf("--");if(_copiaPadre!=-1){_botonPresionado=event.target.id.substring(0,event.target.id.lastIndexOf("--"));}
else
_botonPresionado=event.target.id;var _intervenciones=_navegadorHilo.nodosAgregados;var _Padre=buscarIntervencionPorId(_botonPresionado,_intervenciones);$("#arbol").empty();$("#arbol").unbind();$("#arbol").tree=null;_navegadorHilo.setNavegadorHilo(_Padre);$("body").css("cursor","default");}
DialogBrowser.prototype.agregarNodoSolitario=function(nodo){var _nuevoBtn="<div onclick=\"btnSeleccionarNodo_Click(event, Navegador)\" class=\"Boton\" id=\""+nodo.idIntervencion+"\">"+nodo.usuario+"</div>";$("#dialogBrowser").append(_nuevoBtn);$("#"+nodo.idIntervencion).offset(function(){var a=new Array();a.top=$("#dialogBrowser").offset().top+nodo.CoordenadaY;a.left=$("#dialogBrowser").offset().left+nodo.CoordenadaX;return a;});$("#"+nodo.idIntervencion).css("cursor","pointer");$("#"+nodo.idIntervencion).tipsy({gravity:'s',html:true,bgcolor:"#005190",txtcolor:"#dddddd",title:function(){var text=nodo.Texto;var _recorte=text.split(" ");var _texto="<b>Texto:</b><br>";if(_recorte.length>4){for(var i=0;i<4;i++){_texto+=_recorte[i]+" ";}
_texto+="...";}else
_texto+=nodo.Texto;return _texto;}});}
DialogBrowser.prototype.isNodeOverALine=function(nodo){var _contenido=$("#dialogBrowser").children();var _lineaHorizontal=new Array();for(var i=0;i<_contenido.length;i++){if(_contenido[i].classList[0]=="linea"&&_contenido[i].classList[1]=="horizontal"){_lineaHorizontal.push(_contenido[i]);}}
for(i=0;i<_lineaHorizontal;i++){var pos=$("#"+_lineaHorizontal[i].id).offset();var ancho=$("#"+_lineaHorizontal[i].id).width();var fin=pos.left+ancho;var nodoPos=$("#"+nodo.idIntervencion).offset();var nodoAncho=$("#"+nodo.idIntervencion).outerWidth();var rightSide=nodoPos.left+nodoAncho;if(fin>rightSide)
return true;}
return false;}
DialogBrowser.prototype.escapeHtml=function(string){var _ret=string.replace(/<br>/gi,"\n");_ret=_ret.replace(/<div align="center">|<div align="left">|<div align="right">/gi,"");_ret=_ret.replace(/<i>|<u>|<b>/gi,"");_ret=_ret.replace(/<\/div>|<\/b>|<\/i>|<\/u>/gi,"");return _ret;}
DialogBrowser.prototype.agregarNodoVecino=function(nodo,padre){try{var _nodoPadre=this.buscarNodo(padre);if(this.ultimoUsuario!=nodo.usuario){this.posx++;nodo.setCoordenadaX(this.posx);nodo.setCoordenadaY(++_nodoPadre.AlturaHijo);var _nuevoBtn="<div onclick=\"btnSeleccionarNodo_Click(event, Navegador)\" class=\"Boton\" id=\""+nodo.idIntervencion+"\">"+nodo.usuario+" </div>";$("#dialogBrowser").append(_nuevoBtn);$("#"+nodo.idIntervencion).offset(function(){var a=new Array();a.top=$("#dialogBrowser").offset().top+nodo.CoordenadaY;a.left=$("#dialogBrowser").offset().left+nodo.CoordenadaX;return a;});if(this.isNodeOverALine(nodo)){alert("Nodo está sobre una línea");_nodoPadre.AlturaHijo+=2;nodo.setCoordenadaY(_nodoPadre.AlturaHijo);$("#"+nodo.idIntervencion).offset(function(){var a=new Array();a.top=$("#dialogBrowser").offset().top+nodo.CoordenadaY;a.left=$("#dialogBrowser").offset().left+nodo.CoordenadaX;return a;});}
$("#"+nodo.idIntervencion).css("cursor","pointer");$("#"+nodo.idIntervencion).tipsy({gravity:'s',html:true,bgcolor:"#005190",txtcolor:"#dddddd",title:function(){var text=nodo.Texto;var _recorte=text.split(" ");var _texto="<b>Texto:</b><br>";if(_recorte.length>4){for(var i=0;i<4;i++){_texto+=_recorte[i]+" ";}
_texto+="...";}else
_texto+=nodo.Texto;_texto+="<br><b>En respuesta a:</b><br>";_texto+=padre.Texto;return _texto;}});this.ultimoUsuario=nodo.usuario;if(nodo.CoordenadaY!=_nodoPadre.CoordenadaY){this.copiarNodoPadre(_nodoPadre,nodo);}else{nodoPadre=_nodoPadre;$("#dialogBrowser").append("<hr class=\"linea horizontal\" id=\""+nodo.idIntervencion+padre.idIntervencion+"\"/>");$("#"+nodo.idIntervencion+padre.idIntervencion).offset(function(){var a=Array();a.top=$("#"+padre.idIntervencion).offset().top+$("#"+padre.idIntervencion).outerHeight()/2;a.left=$("#"+padre.idIntervencion).offset().left+$("#"+nodoPadre.idIntervencion).outerWidth();return a;});var nP=$("#"+nodoPadre.idIntervencion).offset().left;var nN=$("#"+nodo.idIntervencion).offset().left-$("#"+nodo.idIntervencion).outerWidth()+2;var ancho=nN-nP;$("#"+nodo.idIntervencion+padre.idIntervencion).width(ancho);$("#"+nodo.idIntervencion+padre.idIntervencion).prop("title","Respuesta a:\n"+this.escapeHtml(nodoPadre.Texto));}}else{nodo.setCoordenadaX(this.posx);_nodoPadre.AlturaHijo++;nodo.setCoordenadaY(_nodoPadre.AlturaHijo);var _nuevo="<div onclick=\"btnSeleccionarNodo_Click(event, Navegador)\" class=\"Boton\" id=\""+nodo.idIntervencion+"\">"+nodo.usuario+"</div>";$("#dialogBrowser").append(_nuevo);node=nodo;$("#"+nodo.idIntervencion).offset(function(){var a=new Array();a.top=$("#dialogBrowser").offset().top+node.CoordenadaY;a.left=$("#dialogBrowser").offset().left+node.CoordenadaX;return a;});$("#"+nodo.idIntervencion).css("cursor","pointer");$("#"+nodo.idIntervencion).tipsy({gravity:'s',html:true,bgcolor:"#005190",txtcolor:"#dddddd",title:function(){var text=nodo.Texto;var _recorte=text.split(" ");var _texto="<b>Texto:</b><br>";if(_recorte.length>4){for(var i=0;i<4;i++){_texto+=_recorte[i]+" ";}
_texto+="...";}else
_texto+=nodo.Texto;_texto+="<br><b>En respuesta a:</b><br>";_texto+=padre.Texto;return _texto;}});this.copiarNodoPadre(_nodoPadre,nodo);}}catch(ex){alert(ex);}}
DialogBrowser.prototype.copiarNodoPadre=function(nodoPadre,siguiente){try{nodoPadre.AlturaHijo++;_origen=nodoPadre.idIntervencion;var _nuevo="<div onclick=\"btnSeleccionarNodo_Click(event, Navegador)\" class=\"Boton\" id=\""+nodoPadre.idIntervencion+"--"+siguiente.idIntervencion+"\">"+nodoPadre.usuario+"</div>";var _nuevoId=nodoPadre.idIntervencion+"--"+siguiente.idIntervencion;$("#dialogBrowser").append(_nuevo);$("#"+nodoPadre.idIntervencion+"--"+siguiente.idIntervencion).offset(function(){var a=new Array();a.top=$("#dialogBrowser").offset().top+siguiente.CoordenadaY;a.left=$("#dialogBrowser").offset().left+nodoPadre.CoordenadaX;return a;});$("#"+nodoPadre.idIntervencion+"--"+siguiente.idIntervencion).css("opacity",0.8);$("#"+nodoPadre.idIntervencion+"--"+siguiente.idIntervencion).css("cursor","pointer");$("#"+nodoPadre.idIntervencion+"--"+siguiente.idIntervencion).tipsy({gravity:'s',html:true,txtcolor:"#dddddd",bgcolor:"#005190",title:function(){return nodoPadre.Texto;}});var _botones=$("#dialogBrowser").children();{var _union="<hr class=\"linea vertical\" id=\""+nodoPadre.idIntervencion+"_"+siguiente.idIntervencion+"\"/>";$("#dialogBrowser").append(_union);var _dibujarLinea=true;var _punto1=_origen;try{var mayorY=0;for(var i=0;i<_botones.length;i++){try{var _el=_botones[i];var _x=$("#"+_el.id).offset().left;var _y=$("#"+_el.id).offset().top;if(_y>mayorY&&_x==nodoPadre.CoordenadaX&&_y>nodoPadre.CoordenadaY&&_el.id!=_nuevoId){_punto1=_el;mayorY=_y;var _newId=_nuevoId.split("--")[0]
if(_el.id.toString()!=_newId[0].toString()){_dibujarLinea=false;}}}catch(ex){alert(ex);}}}catch(ex){alert(ex);}
if(_dibujarLinea){var _idVertical=nodoPadre.idIntervencion+"_"+siguiente.idIntervencion;$("#"+_idVertical).offset(function(){var a=Array();a.top=$("#"+_punto1).offset().top+$("#"+_punto1).outerHeight()-1;a.left=$("#"+_punto1).offset().left+$("#"+nodoPadre.idIntervencion).outerWidth()/2;return a;});$("#"+_idVertical).height(function(){var _inicio=$("#"+nodoPadre.idIntervencion).offset().top;var _fin=$("#"+_nuevoId).offset().top-$("#"+_nuevoId).outerHeight()+1;return _fin-_inicio;});$("#"+_idVertical).prop("title","Respuesta a: \n"+this.escapeHtml(nodoPadre.Texto));}}
{_union="<hr class=\"linea horizontal\" id=\""+nodoPadre.idIntervencion+"_-"+siguiente.idIntervencion+"\"/>";$("#dialogBrowser").append(_union);_punto1=_nuevoId;var _punto2=siguiente.idIntervencion;var _idHorizontal=nodoPadre.idIntervencion+"_-"+siguiente.idIntervencion;$("#"+_idHorizontal).offset(function(){var a=Array();a.top=$("#"+_punto1).offset().top+$("#"+_punto1).outerHeight()/2;a.left=$("#"+_punto1).offset().left+$("#"+_punto1).outerWidth();return a;});$("#"+_idHorizontal).width(function(){var _inicio=$("#"+_punto1).offset().left;var _fin=$("#"+_punto2).offset().left-$("#"+_punto2).outerWidth();if(_fin-_inicio>0)
return _fin-_inicio+3;else
return 0;});$("#"+_idHorizontal).prop("title","Respuesta a:\n"+this.escapeHtml(nodoPadre.Texto));}}catch(ex){alert(ex);}}
DialogBrowser.prototype.buscarNodo=function(intervencion){for(var i=0;i<this.coleccionNodos.length;i+=1){if(this.coleccionNodos[i].idIntervencion==intervencion.idIntervencion){return this.coleccionNodos[i];}}
return null;}
function NodoBrowser(contenido){this.contenido=contenido;this.pos_X;this.pos_Y=10;this.AlturaHijo;this.CoordenadaX;this.CoordenadaY;this.idIntervencion=contenido.idIntervencion;this.usuario=contenido.usuarioCreador.nombreUsuario;this.Texto=contenido.Texto;this.textoRespuesta=contenido.TextoRespuesta;}
NodoBrowser.prototype.setCoordenadaX=function(x){if(x==0||x==1){x=1;this.pos_X=10;this.CoordenadaX=this.pos_X;}else{this.pos_X=x*120;this.CoordenadaX=this.pos_X;}}
NodoBrowser.prototype.setCoordenadaY=function(y){this.AlturaHijo=y;if(y==0)
y=1;this.pos_Y=y*30;this.CoordenadaY=this.pos_Y;if(y>1){this.pos_Y+=10;this.CoordenadaY=this.pos_Y;}
if(y>2){this.pos_Y+=10*y;this.CoordenadaY=this.pos_Y;}}