
$(function(){$("span.title").css("cursor","default");$(".controlDisplayIntervencionContainer").css("cursor","default");$(".controlDisplayIntervencionBotonera").css("cursor","default");$(".controlDisplayIntervencionTexto").css("cursor","default");$(".controlDisplayIntervencionImagenContainer").css("cursor","default");$(".btnVerContextoContainer").css("cursor","default");$(".tipoMovidaContainer").css("cursor","default");});function NavegadorHilo(){var me=this;me._ventanaPadre=new Array();me.modoFacilitador;me.tiposMovida=new Object();me.nodosAgregados;me.Templatecontenido;{me.nodosAgregados=new Array();}
NavegadorHilo.prototype.setVentanaPadre=function(clasePadre){me._ventanaPadre=clasePadre;}
NavegadorHilo.prototype.setTiposMovida=function(tiposMovida){me.tiposMovida=tiposMovida;}
NavegadorHilo.prototype.setModoFaciliador=function(valor){me.modoFacilitador=valor;}
NavegadorHilo.prototype.agregarControlDisplayTextoIntervencion=function(param,isRaiz){var ret="<div class=\"controlDisplayIntervencionContainer ui-corner-all\" style=\"width: 700px;\">";if(isRaiz){ret+="<div class=\"btnVerContextoContainer\" style=\"width: 520px\"><i>Publicado por "+param.usuarioCreador.nombreUsuario+" el "+param.FechaCreacion+"</i>";}else{ret+="<div class=\"btnVerContextoContainer\" style=\"width: 520px\"><i>Publicado por "+param.usuarioCreador.nombreUsuario+" el "+param.FechaCreacion+" en respuesta a "+param.intervencionRespuesta.usuarioCreador.nombreUsuario+"</i>"+"<button id=\"verCont_"+param.idIntervencion+"\" class=\"btnVerContexto\">"+"Ver contexto"+" </button>";}
ret+="</div>"+"<div class=\"tipoMovidaContainer \" style=\"width:180px; font-size:11px; \">";if(param.correccionMovida!=null&&param.correccionMovida.length>0){for(var i=0;i<me.tiposMovida.length;i++){if(me.tiposMovida[i].IdMovida==param.correccionMovida[0].IdMovida){ret+=me.tiposMovida[i].Nombre;}}}else{ret+=param.tipoMovida.Nombre;}
ret+="</div>"+"<div class=\"clear\"></div>"+"<div class=\"controlDisplayIntervencionContexto controlDisplayIntervencionContextoOut\" id=\"contexto_"+param.idIntervencion+"\" style=\"width: 695px;\"><i>";if(param.intervencionRespuesta!=null){ret+=param.TextoRespuesta;}
ret+="</i></div>"+"<div class=\"controlDisplayIntervencionImagenContainer\" style=\"width:50px; margin-left:3px;\">"+"<img alt=\"avatar_"+param.usuarioCreador.nombreUsuario+"\" src=\""+param.usuarioCreador.imagen+"\" width=\"50\" height=\"\" >"+"</div>"+"<div class=\"controlDisplayIntervenciontexto\" id=\"textoIntervencion_"+param.idIntervencion+"\" style=\"width:640px; height:55px; overflow:auto\" >"+
me.separaEnParrafos(param.Texto)+"</div>"+"<div class=\"clear\"></div>"+"<div class=\"controlDisplayIntervencionBotonera\">"+"<button class =\"btnEscribirNota\" id=\"escribeNota_"+param.idIntervencion+"\">Escribir nota...</button>"+"<button class =\"btnAgregarMarcador\" id=\"agregaMarcadores_"+param.idIntervencion+"\">Agregar a marcadores</button>"+"<button class =\"btnResponderATodo\" id=\"respondeTodo_"+param.idIntervencion+"\">Responder a todo</button>";if(me.modoFacilitador){ret+="<button class=\"btnSugerirCorreccion\" id=\"btnSugerirCorreccion"+param.idIntervencion+"\" style=\"float:right; margin-top: 3px; line-height: 15px;\">Corregir</button>";}else{ret+="<button class=\"btnSugerirCorreccion\" id=\"btnSugerirCorreccion"+param.idIntervencion+"\" style=\"float:right; margin-top: 3px; line-height: 15px;\">Sugerir</button>";}
ret+="<select class=\"cmbTipoMovidas\" id=\"cmbTipoMovidas_"+param.idIntervencion+"\" style=\" width: 130px; float:right; margin-top:5px;\"><select>"+"</div>"+"</div>";return ret;}
NavegadorHilo.prototype.separaEnParrafos=function(texto){var _parrafos=texto.split("<br>");var _nuevoTexto="";for(var i=0;i<_parrafos.length;i++){_nuevoTexto+="<div class=\"parrafo\">"+_parrafos[i]+"</div>";}
return _nuevoTexto;}
NavegadorHilo.prototype.limpiar=function(){$("#arbol").tree("destroy");me.nodosAgregados=new Array();}
NavegadorHilo.prototype.agregarNodoRaiz=function(intraiz){var _imagenUsuario=me._ventanaPadre.getImage(intraiz.usuarioCreador.nombreUsuario);intraiz.usuarioCreador.imagen=_imagenUsuario;var _nuevo=new NodoHilo();_nuevo.id=intraiz.idIntervencion;_nuevo.intervencion=intraiz;_nuevo.label=me.agregarControlDisplayTextoIntervencion(intraiz,true);_nuevo.children=new Array();_nuevo.Nivel=1;me.nodosAgregados.push(_nuevo);}
NavegadorHilo.prototype.agregarNodos=function(listaIntervenciones){for(var i=0;i<listaIntervenciones.length;i++){var _imagenUsuario=me._ventanaPadre.getImage(listaIntervenciones[i].usuarioCreador.nombreUsuario);listaIntervenciones[i].usuarioCreador.imagen=_imagenUsuario;}
for(var i=0;i<listaIntervenciones.length;i++){try{if(listaIntervenciones[i].intervencionRespuesta!=null){var _agregarNodo=false;var _nuevo=null;for(var j=0;j<me.nodosAgregados.length;j++){try{if(listaIntervenciones[i].intervencionRespuesta.idIntervencion==me.nodosAgregados[j].id){_nuevo=new NodoHilo();_agregarNodo=true;_nuevo.id=listaIntervenciones[i].idIntervencion;_nuevo.intervencion=listaIntervenciones[i];_nuevo.label=me.agregarControlDisplayTextoIntervencion(listaIntervenciones[i],false);_nuevo.Nivel=me.nodosAgregados[j].Nivel+1;me.nodosAgregados[j].children.push(_nuevo);break;}}catch(ex){}}}
else{}}catch(ex){alert(ex);}
if(_agregarNodo){me.nodosAgregados.push(_nuevo);}}}
NavegadorHilo.prototype.setNavegadorHilo=function(listaAnidada){var data=new Array();data[0]=listaAnidada;$('#arbol').tree({data:data,autoOpen:true,dragAndDrop:false,saveState:false,selectable:false});{var _contextMenu=new responderContextMenu();_contextMenu.ventanaPadre=me;_contextMenu.setMenu();if(me.modoFacilitador)
$(".cmbTipoMovidas").prop("title","¿Desea corregir la movida?");else
$(".cmbTipoMovidas").prop("title","¿Desea sugerir otra movida?");$(".btnVerContexto").button();$(".btnVerContexto").click(function(){var p=$(this);var id=p[0].id.split("_");$("#contexto_"+id[1]).toggleClass("controlDisplayIntervencionContextoOut",100);return false;});$(".btnEscribirNota").button({icons:{primary:'ui-icon-document'}});$(".btnEscribirNota").prop("title","Permite ver y agregar notas asociadas a esta intervención. Las intervenciones son personales.");$(".btnEscribirNota").click(function(){me.abrirNotas(this.id.replace("escribeNota_",""));});$(".btnAgregarMarcador").button({icons:{primary:'ui-icon-agregarmarcadores'}});$(".btnAgregarMarcador").prop("title","Agrega esta intervención a la lista de marcadores.");$(".btnAgregarMarcador").click(function(){me.agregarMarcador(this.id.replace("agregaMarcadores_",""));});$(".btnResponderATodo").button({icons:{primary:'ui-icon-responderatodo'}});$(".btnResponderATodo").click(function(){var p=$(this);var id=p[0].id.split("_");var _nodoArbol=$("#arbol").tree('getNodeById',id[1]);me._ventanaPadre.agregarTabRespuesta(_nodoArbol.intervencion,_nodoArbol.intervencion.Texto);});$(".btnSugerirCorreccion").click(function(){var idIntervencion=this.id;idIntervencion=idIntervencion.replace("btnSugerirCorreccion","");var _selectedOption=$("#cmbTipoMovidas_"+idIntervencion+" option:selected").val();var _seleccionada;for(var i=0;i<me.tiposMovida.length;i++){if(me.tiposMovida[i].Nombre==_selectedOption){_seleccionada=me.tiposMovida[i];}}
me.sugerirIntervencion(idIntervencion,_seleccionada);});for(var i=0;i<me.tiposMovida.length;i++){$(".cmbTipoMovidas").append("<option>"+me.tiposMovida[i].Nombre+"</option>");}
$(".controlDisplayIntervencionContexto div").css("cursor","default");$(".controlDisplayIntervenciontexto div").css('cursor','text');}}
NavegadorHilo.prototype.responderParrafo=function(texto,idIntervencion){try{var _n=me.buscarNodo(idIntervencion.split("_")[1]);if(_n!=null){_n.intervencion.Texto=texto;me._ventanaPadre.agregarTabRespuesta(_n.intervencion,texto);}}catch(ex){alert(ex);}}
NavegadorHilo.prototype.buscarNodo=function(idIntervencion){for(var i=0;i<me.nodosAgregados.length;i++){if(me.nodosAgregados[i].id==idIntervencion){return me.nodosAgregados[i];}}
return null;}
NavegadorHilo.prototype.respondeTodo=function(textoIntervencion){alert(textoIntervencion.innerHTML+" ,"+textoIntervencion.id.split("_")[1]);}
NavegadorHilo.prototype.agregarMarcador=function(origen){var _n=me.buscarNodo(origen);me._ventanaPadre.agregarMarcador(_n.intervencion);}
NavegadorHilo.prototype.abrirNotas=function(origen){try{var _n=me.buscarNodo(origen);me._ventanaPadre.abrirVentanaNotas(_n.intervencion);}catch(ex){}}
NavegadorHilo.prototype.sugerirIntervencion=function(idIntervencion,movida){var _n=new NodoHilo();_n=me.buscarNodo(idIntervencion);me._ventanaPadre.guardarSugerenciaMovida(_n.intervencion,movida);}}
function NodoHilo(){this.label;this.children=new Array();this.id;this.values;this.Nivel;this.intervencion=new Intervencion();}