
$(function(){$("#moves").hide();$("#tabs").tabs({selected:1,show:function(event,ui){if(ui.index==0){$("#dgReglas").dataTable().fnAdjustColumnSizing(true);}}});$("#tab3").hide();$("#todasActas").hide();$("#btnVerEstadisticas").button({icons:{primary:"ui-icon-clipboard"}});$("#controlTab").tabs();$("#btnRefrescar").button();$("#btnGuardarActa").button();$("#btnParticipar").button();$("#btnConfigurar").button();$("#btnVerTodasActas").button();$("#btnVerTodasActas").hide();$("#txtActaUsuario").wysiwyg({controls:{bold:{visible:true},italic:{visible:true},underline:{visible:true},separator00:{visible:true},justifyLeft:{visible:true},justifyCenter:{visible:true},justifyRight:{visible:true}}});$("#lblIntervencion").css("display","none");{var _sesionActual=JSON.parse($("#sesionActual").val());var _idDialogo=$("#idDialogo").val();var _idIntervencion=$("#idIntervencion").val();vdialogo=new VentanaDialogo(_sesionActual,_idDialogo);if(_idIntervencion!=null){vdialogo.seleccionarIntervencion(_idIntervencion);}}});function none(){alert($("#txtActaUsuario").val());}
var Controlador;function VentanaDialogo(sesionActual,idDialogo){me=this;this.sesion=sesionActual;vNotas=new Array();this.listaNodos=new Array();this.actas=new Array();this.controlTextoIntervencion=new controlEscrituraIntervencion();Controlador=new CDialogo(sesionActual);var _exito=Controlador.actualizarDialogoActual(idDialogo);me.crearTablaReglas();if(_exito){controlHilo=new DialogBrowser();Navegador=new NavegadorHilo();Navegador.setVentanaPadre(this);var _dialogo=Controlador.dialogoActual;this.cargarDialogo(_dialogo);this.initializeComponents();}}
window.onbeforeunload=function(){for(var i=0;i<vNotas.length;i++){vNotas[i].close();}}
VentanaDialogo.prototype.seleccionarIntervencion=function(idIntervencion){var _intSeleccionada=null;for(var i=0;i<Controlador.dialogoActual.intervenciones.length;i++){if(Controlador.dialogoActual.intervenciones[i].idIntervencion==idIntervencion){_intSeleccionada=Controlador.dialogoActual.intervenciones[i];break;}}
this.seleccionarIntervencion_2(_intSeleccionada);}
VentanaDialogo.prototype.seleccionarIntervencion_2=function(intSeleccionada){try{Navegador.limpiar();controlHilo=new DialogBrowser();controlHilo.intervenciones=Controlador.getIntervencionesActuales();controlHilo.refrescar();Navegador.agregarNodoRaiz(controlHilo.intervenciones[0]);Navegador.agregarNodos(controlHilo.intervenciones);var todasLasIntervenciones=Navegador.nodosAgregados;$("#arbol").tree('destroy');var sel;for(var i=0;i<todasLasIntervenciones.length;i++){if(todasLasIntervenciones[i].id==intSeleccionada.idIntervencion){sel=todasLasIntervenciones[i];}}
Navegador.setNavegadorHilo(sel);$("#"+intSeleccionada.idIntervencion).css("border","solid 1px #ff6600");$("#dialogBrowser").click(function(){$("#"+intSeleccionada.idIntervencion).css("border","none");});}catch(ex){}}
VentanaDialogo.prototype.agregarMarcador=function(intervencion){var _controlador=new CMarcadores();var _err="";var _exito=_controlador.guardarMarcador(Controlador.SesionActual,intervencion,_err);if(_exito){notificar("Marcador guardado exitosamente");}
else{notificar("No se pudo guardar el marcador: "+_err);}}
VentanaDialogo.prototype.initializeComponents=function(){$("#btnRefrescar").click(function(){me.btnRefrescar_Click(this);});$("#cmbUsuarios").change(function(event){me.cmbUsuarios_SelectionChanged(this,event);});$("#btnVerTodasActas").click(function(){me.btnVerTodasActas_Click(this);});$("#btnParticipar").click(function(){me.btnParticipar_Click(this);});$("#btnGuardarActa").click(function(){me.btnGuardarActa_Click(this);});$("#btnVerEstadisticas").click(function(){me.btnVerEstadisticas_Click(this);});$("#btnConfigurar").click(function(){me.btnConfigurar_Click(this);});}
VentanaDialogo.prototype.btnConfigurar_Click=function(sender){vNotas[vNotas.length]=window.open("VentanaConfigurarDialogo.php","_vnota");}
VentanaDialogo.prototype.btnVerEstadisticas_Click=function(sender){vNotas[vNotas.length]=window.open("VentanaEstadisticas.php","_vnota");}
VentanaDialogo.prototype.btnGuardarActa_Click=function(sender){var _controlador=new CActa(Controlador.SesionActual);try{var _acta=Controlador.dialogoActual.ActaUsuario;_acta.TextoActa=$("#txtActaUsuario").wysiwyg("getContent")[0].value;if($.trim(_acta.TextoActa)==""){return;}
var _msgError="";var _exito=_controlador.guardarActa(Controlador.dialogoActual,_acta,_msgError);if(_exito){notificar("El acta fue exitosamente guardada");}
else{notificar("No se pudo guardar el acta.<br>"+_msgError);}}catch(ex){notificar("No se pudo guardar el acta");}}
VentanaDialogo.prototype.btnParticipar_Click=function(sender){$("#tabs").tabs({selected:1});}
VentanaDialogo.prototype.cmbUsuarios_SelectionChanged=function(sender,event){if(sender.selectedIndex<=0){$("#txtActaOtroUsuario").html("");}
var _acta;for(var i=0;i<me.actas.length;i++){if(me.actas[i].UsuarioCreador.nombreUsuario==sender.value){_acta=me.actas[i];}}
try{if(_acta.TextoActa!=null){$("#txtActaOtroUsuario").html(_acta.TextoActa);}}catch(ex){}}
VentanaDialogo.prototype.btnVerTodasActas_Click=function(sender){$("#tab3").show();$("#todasActas").show();$("#txtActaOtroUsuario").html("");$("#tabs").tabs({selected:2});me.actas=Controlador.obtenerTodasLasActas();$("#cmbUsuarios").empty();$("#cmbUsuarios").append("<option></option>");for(var i=0;i<me.actas.length;i++){$("#cmbUsuarios").append("<option>"+me.actas[i].UsuarioCreador.nombreUsuario+"</option>");}}
VentanaDialogo.prototype.btnRefrescar_Click=function(sender){try{var _exito=Controlador.actualizarDialogoActual(Controlador.dialogoActual.idDialogo);if(_exito){var _dialogo=Controlador.dialogoActual;this.cargarDialogo(_dialogo);}}catch(ex){}}
VentanaDialogo.prototype.crearTablaReglas=function(){$("#dgReglas").dataTable({"bJQueryUI":true,"bPaginate":false,"bScrollInfinite":true,"sScrollY":"150px","bScrollCollapse":true,"bServerSide":false,"bFilter":false,"oLanguage":{"sInfo":"Mostrando _TOTAL_ reglas asociadas","sProcessing":"Cargando...","sEmptyTable":"No hay reglas asociadas","sInfoEmpty":""},"aoColumns":[{"sTitle":"Reglas","bSortable":true,"sWidth":"100%"}]});}
VentanaDialogo.prototype.cargarDialogo=function(dialogo){try{document.title="Dialogando - "+dialogo.Titulo;$("#tituloPaginaActual a").text("Dialogando - "+dialogo.Titulo);$("#lblTitulo").text(dialogo.Titulo);$("#lblFechaCreacion").text(dialogo.FechaCreacion);$("#lblNombreUsuario").text(dialogo.usuarioCreador.nombreCompleto+" ("+dialogo.usuarioCreador.nombreUsuario+")");$("#dgReglas").dataTable().fnDestroy();$("#dgReglas tbody").empty();me.crearTablaReglas();for(var i=0;i<dialogo.Reglas.length;i++){$("#dgReglas").dataTable().fnAddData([dialogo.Reglas[i].textoRegla]);}}catch(ex){}
try{if(dialogo.ActaUsuario.TextoActa!=null){$("#txtActaUsuario").wysiwyg('setContent',dialogo.ActaUsuario.TextoActa);}}catch(ex){}
try{Navegador.setTiposMovida(dialogo.categoria.movidas);}catch(ex){}
try{var _usu=Controlador.SesionActual.usuario;if(_usu.Rol==_usu.ROL_ADMINISTRADOR||(_usu.nombreUsuario==dialogo.usuarioFacilitador.nombreUsuario)){$("#btnVerTodasActas").show();Navegador.modoFacilitador=true;$("#btnConfigurar").css("visibility","visible");$("#btnParticipar").hide();}else{$("#btnVerTodasActas").hide();Navegador.modoFacilitador=false;$("#btnConfigurar").css("visibility","hidden");}}catch(ex){}
try{var _csesion=new CSesion();dialogo.usuarioCreador.imagen=_csesion.obtenerArchivoUsuario("",dialogo.usuarioCreador.nombreUsuario);$("#imagenUsuario img").prop("src",dialogo.usuarioCreador.imagen);}catch(ex){}
try{}catch(ex){}
controlHilo=new DialogBrowser();controlHilo.intervenciones=Controlador.getIntervencionesActuales();controlHilo.refrescar();Navegador.limpiar();Navegador.agregarNodoRaiz(controlHilo.intervenciones[0]);Navegador.agregarNodos(controlHilo.intervenciones);Navegador.setNavegadorHilo(Navegador.nodosAgregados[0]);}
VentanaDialogo.prototype.remueveTabdeLista=function(idInter){for(var i=0;i<this.listaNodos.length;i++){if(this.listaNodos[i].ContenidoAsociado.idIntervencion==idInter){this.listaNodos[i]=null;}}}
VentanaDialogo.prototype.buscarTab=function(inter){for(var i=0;i<this.listaNodos.length;i++){if(this.listaNodos[i].ContenidoAsociado.idIntervencion==inter.idIntervencion){return this.listaNodos[i];}}
return null;}
VentanaDialogo.prototype.buscarNodoWidget=function(control){try{for(var i=0;i<this.listaNodos.length;i++){if(this.listaNodos[i].ContenidoAsociado.idIntervencion==control){return this.listaNodos[i];}}
return null;}catch(ex){}
return null;}
VentanaDialogo.prototype.guardarSugerenciaMovida=function(intervencion,movida){var _err="";var _exito=Controlador.guardarSugerencia(intervencion,movida,_err);if(_exito){notificar("Sugerencia guardada con éxito");}else{notificar("No se pudo guardar la sugerencia: "+_err);}}
VentanaDialogo.prototype.agregarTabRespuesta=function(intervencion,texto){if(this.listaNodos.length==0){}
var _nodoExiste=this.buscarTab(intervencion);if(_nodoExiste==null){var _nuevoNodo=new Nodo(intervencion,texto);this.listaNodos.push(_nuevoNodo);lista=this.listaNodos;$tabs=$("#controlTab").tabs({add:function(event,ui){var tab_content=generaControlEscrituraIntervencion(intervencion.idIntervencion);$(ui.panel).append(tab_content);{$("#cmbTipoIntervencion_"+intervencion.idIntervencion).change(function(){for(var i=0;i<Navegador.tiposMovida.length;i++){if($("#cmbTipoIntervencion_"+intervencion.idIntervencion+" option:selected").val()==Navegador.tiposMovida[i].Nombre){$("#cmbTipoIntervencion_"+intervencion.idIntervencion).prop("title",Navegador.tiposMovida[i].descripcion);$("#lblExplicacionMovida_"+intervencion.idIntervencion).html(Navegador.tiposMovida[i].descripcion);}}});me.controlTextoIntervencion.setComboMovidas(Controlador.tipodeMovidasActuales);$("#btnEnviar_"+intervencion.idIntervencion).button();$("#btnEnviar_"+intervencion.idIntervencion).click(function(){var _idIntervencion=this.id.replace("btnEnviar_","");var _htmlString=$("#txtIntervencion_"+_idIntervencion).val();var _seleccionado=$("#cmbTipoIntervencion_"+_idIntervencion+" option:selected").val();var _valor=null;for(var i=0;i<Navegador.tiposMovida.length;i++){if(Navegador.tiposMovida[i].Nombre==_seleccionado){_valor=Navegador.tiposMovida[i];}}
me.publicarIntervencion(_idIntervencion,_valor,_htmlString);});$("#btnCancelar_"+intervencion.idIntervencion).button();$("#btnCancelar_"+intervencion.idIntervencion).mouseover(function(){$("#tab_"+intervencion.idIntervencion).tipsy("hide");});$("#btnCancelar_"+intervencion.idIntervencion).click(function(){var _p=$(this)[0].id.replace("btnCancelar","tab");$("#controlTab").tabs("remove",_p);for(var i=0;i<lista.length;i++){if(lista[i].ContenidoAsociado.idIntervencion==intervencion.idIntervencion){lista.splice(i,1);}}});$("#txtIntervencion_"+intervencion.idIntervencion).wysiwyg({controls:{bold:{visible:true},italic:{visible:true},underline:{visible:true},separator00:{visible:true},justifyLeft:{visible:true},justifyCenter:{visible:true},justifyRight:{visible:true}}});}
$(this).focus();}});var identificador_tab=intervencion.idIntervencion;$("#controlTab").tabs("add","#tab_"+identificador_tab,"Respuesta a "+_nuevoNodo._textoTitulo);$("#controlTab").tabs("select","tab_"+identificador_tab);$("#tab_"+identificador_tab).prop("title","Respuesta para "+me.escapeHtml(intervencion.Texto));location.href="#final";$(".cmbTipoIntervencion").change();}
else{}}
VentanaDialogo.prototype.escapeHtml=function(string){var _ret=string.replace(/<br>/gi,"\n");_ret=_ret.replace(/<div align="center">|<div align="left">|<div align="right">/gi,"");_ret=_ret.replace(/<i>|<u>|<b>/gi,"");_ret=_ret.replace(/<\/div>|<\/b>|<\/i>|<\/u>/gi,"");return _ret;}
VentanaDialogo.prototype.abrirVentanaNotas=function(intervencion){intervencion.Texto="";if(intervencion.intervencionRespuesta!=null)
intervencion.intervencionRespuesta.Texto="";for(var i=0;i<vNotas.length;i++){if(vNotas[i].closed){vNotas.splice(i,1);i=0;}}
var abrirNueva=true;var vNotaActual=null;if(vNotas.length>0){for(var i=0;i<vNotas.length;i++){if(vNotas[i].idIntervencion==intervencion.idIntervencion){abrirNueva=false;vNotaActual=vNotas[i];break;}}}else{abrirNueva=true;}
if(abrirNueva){var ventanaNotaActual=window.open("VentanaNotas.php?intervencion="+JSON.stringify(intervencion.idIntervencion),"vNota_"+intervencion.idIntervencion,"width=320,height=300,location=no,resizable=no");vNotas.push(ventanaNotaActual);}else{vNotaActual.focus();}}
VentanaDialogo.prototype.publicarIntervencion=function(idIntervencion,codigoMovida,texto){var _nodoOrigen=this.buscarNodoWidget(idIntervencion);if($.trim(texto)==""){return;}
_nodoOrigen.ContenidoAsociado.TextoRespuesta=_nodoOrigen.Texto;var _exito=Controlador.publicarIntervencion(_nodoOrigen.ContenidoAsociado,texto,codigoMovida);if(_exito){try{notificar("La intervención fue guardada");$("#controlTab").tabs("remove","tab_"+idIntervencion);for(var i=0;i<this.listaNodos.length;i++){if(this.listaNodos[i].ContenidoAsociado.idIntervencion==idIntervencion){this.listaNodos.splice(i,1);}}
_exito=Controlador.actualizarDialogoActual(Controlador.dialogoActual.idDialogo);if(_exito){var _dialogo=Controlador.dialogoActual;this.cargarDialogo(_dialogo);}}
catch(ex){}}else{notificar("No se pudo guardar la intervención.");}}
VentanaDialogo.prototype.getImage=function(usuario){try{if(usuario.imagen==null){var _csesion=new CSesion();var _file=_csesion.obtenerArchivoUsuario(Controlador.SesionActual,usuario);}
return _file;}catch(ex){}
return;}
function generaControlEscrituraIntervencion(idIntervencionResponder){_ret="<div>"+"<label for=\"intervencion\" class=\"lblIntervencion\">Texto de la intervención</label>"+"<div class=\"intervencion\" >"+"<textarea class=\"txtIntervencion\" id=\"txtIntervencion_"+idIntervencionResponder+"\" cols=\"105\"></textarea>"+"</div> "+"<div class=\"clear\" style=\"height: 10px;\"></div>"+"<div class=\"tipoIntervencion\" style=\"float: left; width: 200px;\">"+"<label for=\"cmbTipoIntervencion\" class=\"lblTipoIntervencion\">Tipo de intervención:</label>"+"<select class=\"cmbTipoIntervencion\" id=\"cmbTipoIntervencion_"+idIntervencionResponder+"\" style=\"float: left; width: 200px;\">"+"</select>"+" </div>"+"<div class=\"grid_3 lblExplicacionMovida\" id=\"lblExplicacionMovida_"+idIntervencionResponder+"\" style=\"height: 50px; float:left; overflow:auto;\"></div>"+" <div class=\"botonesIntervencion\" style=\"float: left; margin-left: 10px; margin-top: 5px; \">"+"<button class=\"btnEnviar\" id=\"btnEnviar_"+idIntervencionResponder+"\">Enviar</button>"+"<button class=\"btnCancelar\" id=\"btnCancelar_"+idIntervencionResponder+"\">Cancelar</button>"+"</div>"+"</div>"+"<div class=\"clear\"></div>";return _ret;}
function Nodo(contenido,TextoRespuesta){this.Tab;this.Texto;this.ContenidoAsociado;this.Widget;if(contenido==null&&TextoRespuesta==null){}else{this.ContenidoAsociado=contenido;this.Texto=TextoRespuesta;this._textoTitulo="";var _txt=TextoRespuesta;if(_txt.substr(1,3)=="div"){var htmlObj=$(_txt);var value=new Array();for(var i=0;i<htmlObj.length;i++){if(htmlObj[i].className=="parrafo"){value[i]=htmlObj[i].innerHTML;}}
_txt="";for(i=0;i<value.length;i++){_txt+=value[i]+" ";}
TextoRespuesta=_txt;}
if(TextoRespuesta.length>10){this._textoTitulo=TextoRespuesta.substr(0,10)+"...";}else{this._textoTitulo=TextoRespuesta;}}}